# Generated by Django 3.2.8 on 2021-10-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('creation_date', models.DateTimeField(editable=False)),
                ('modification_date', models.DateTimeField()),
                ('description', models.TextField(blank=True, max_length=1024)),
                ('image', models.ImageField(blank=True, null=True, upload_to='listings_images')),
                ('slug', models.SlugField(default='title', max_length=128, unique_for_date='created')),
            ],
            options={
                'ordering': ['-modification_date'],
                'index_together': {('id', 'slug')},
            },
        ),
    ]
