# Generated by Django 3.2.8 on 2021-10-18 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0002_alter_listing_slug'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='listing',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='listing',
            name='slug',
        ),
    ]
