# Generated by Django 3.2.8 on 2021-10-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0003_auto_20211018_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='slug',
            field=models.SlugField(default='title', max_length=128, unique_for_date='creation_date'),
        ),
        migrations.AlterIndexTogether(
            name='listing',
            index_together={('id', 'slug')},
        ),
    ]
