# Generated by Django 3.2.8 on 2021-10-18 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fair', '0004_auto_20211018_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_listings', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='modification_date',
            field=models.DateTimeField(editable=False),
        ),
    ]
