# Generated by Django 3.2.8 on 2021-10-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0009_auto_20211020_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='name', max_length=64, unique=True),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', '0')), name='price_non_negative'),
        ),
    ]
