# Generated by Django 3.2.8 on 2021-10-21 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0010_auto_20211020_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
                ('listing_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_listing_1', to='fair.listing')),
                ('listing_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_listing_2', to='fair.listing')),
            ],
        ),
    ]
