# Generated by Django 3.2.8 on 2021-10-22 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0011_similarity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='similarity',
            options={'verbose_name_plural': 'Similarities'},
        ),
    ]
