# Generated by Django 3.2.8 on 2021-10-22 16:21

# generated by ./manage.py makemigrations fair --empty

from django.db import migrations
from fair.auth import AuthTools

def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.create(name=AuthTools.MANAGER)
    Group.objects.create(name=AuthTools.USER)

class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0012_alter_similarity_options'),
    ]

    operations = [
         migrations.RunPython(create_groups)
    ]