# Generated by Django 3.2.8 on 2021-10-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0015_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
                ('instance_id', models.IntegerField()),
                ('data', models.TextField()),
            ],
        ),
    ]
