# Generated by Django 3.2.8 on 2021-10-25 10:02

from django.db import migrations
import fair.encryptions


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0016_deleteddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleteddata',
            name='data',
            field=fair.encryptions.EncryptedTextField(),
        ),
    ]
