# Generated by Django 3.2.8 on 2021-10-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0019_alter_activitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.TextField(),
        ),
    ]
