# Generated by Django 3.2.8 on 2021-10-25 10:54

from django.db import migrations
import fair.encryptions


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0020_alter_activitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=fair.encryptions.EncryptedTextField(max_length=256),
        ),
    ]
