# Generated by Django 3.2.8 on 2021-10-25 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0021_alter_activitylog_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-at'], 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='deleteddata',
            options={'verbose_name_plural': 'DeletedData'},
        ),
    ]
