# Generated by Django 3.2.5 on 2021-10-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0022_auto_20211025_1238'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='listing',
            name='price_non_negative',
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(check=models.Q(('price__gt', '0')), name='price_non_negative'),
        ),
    ]
