# Generated by Django 3.2.5 on 2021-10-30 17:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0023_auto_20211030_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 30, 17, 31, 17, 335034, tzinfo=utc), editable=False),
        ),
    ]
