# Generated by Django 3.2.5 on 2021-11-01 10:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0024_alter_listing_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='slug',
            field=models.SlugField(default='slug', max_length=128),
        ),
    ]
