# Generated by Django 3.2.5 on 2021-11-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0025_auto_20211101_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='slug',
            field=models.SlugField(max_length=128),
        ),
    ]
