# Generated by Django 3.2.5 on 2021-11-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0028_alter_listing_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
